version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: backend-db-xd-zut
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres

volumes:
  postgres:
    name: backend
